# Generated by Django 5.0.14 on 2026-08-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_date", models.DateField(verbose_name="현지 날짜")),
                ("score", models.PositiveSmallIntegerField(verbose_name="컨디션 점수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_conditions",
                        to="trips.trip",
                        verbose_name="여정",
                    ),
                ),
            ],
            options={
                "verbose_name": "하루 컨디션",
                "verbose_name_plural": "하루 컨디션",
                "ordering": ["-local_date"],
            },
        ),
        migrations.CreateModel(
            name="InflightCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("water", "물 마심"),
                            ("walk", "걷기"),
                            ("stretch", "스트레칭"),
                            ("moisturize", "보습"),
                        ],
                        max_length=30,
                        verbose_name="체크 유형",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="횟수"),
                ),
                (
                    "client_event_id",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="클라이언트 이벤트 ID"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발생 시각"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="동기화 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inflight_checks",
                        to="trips.trip",
                        verbose_name="여정",
                    ),
                ),
            ],
            options={
                "verbose_name": "기내 체크",
                "verbose_name_plural": "기내 체크",
            },
        ),
        migrations.CreateModel(
            name="RecoveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="항목명")),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("sleep", "수면"),
                            ("circulation", "순환"),
                            ("hydration", "수분"),
                            ("skin", "피부"),
                        ],
                        max_length=20,
                        verbose_name="요소",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="예정 시각")),
                ("local_date", models.DateField(verbose_name="현지 날짜")),
                (
                    "score_delta",
                    models.PositiveSmallIntegerField(verbose_name="상승 점수"),
                ),
                (
                    "reason_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="이유 문구"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "미완료"), ("completed", "완료")],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시각"
                    ),
                ),
                (
                    "score_applied",
                    models.BooleanField(default=False, verbose_name="점수 반영 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_items",
                        to="trips.trip",
                        verbose_name="여정",
                    ),
                ),
            ],
            options={
                "verbose_name": "회복 항목",
                "verbose_name_plural": "회복 항목",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailycondition",
            constraint=models.UniqueConstraint(
                fields=("trip", "local_date"), name="uniq_daily_condition_per_trip_date"
            ),
        ),
    ]
