# Generated by Django 5.0.14 on 2026-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflightcheck',
            name='check_type',
            field=models.CharField(choices=[('water', '물 마심'), ('stretch', '스트레칭'), ('moisturize', '보습'), ('sleep', '6시간 취침하기')], max_length=30, verbose_name='체크 유형'),
        ),
    ]
