# Generated by Django 5.0.14 on 2026-08-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_alter_inflightcheck_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='카운트'),
        ),
        migrations.AddField(
            model_name='recoveryitem',
            name='key',
            field=models.CharField(blank=True, max_length=30, verbose_name='항목 키'),
        ),
    ]
