# Generated by Django 5.0.14 on 2026-08-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_score', models.PositiveSmallIntegerField(choices=[(0, '평소처럼 다 했어요'), (1, '힘들었지만 계획대로 했어요'), (2, '일부를 줄이거나 짧게 했어요'), (3, '하루치 일정을 미뤘어요'), (4, '하루를 통째로 쉬었어요'), (5, '이틀 이상 영향을 받았어요')], verbose_name='일정 차질도')),
                ('selected_answer', models.CharField(max_length=120, verbose_name='선택 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='trips.trip', verbose_name='여정')),
            ],
            options={
                'verbose_name': '여정 결과',
                'verbose_name_plural': '여정 결과',
                'ordering': ['-created_at'],
            },
        ),
    ]
