# Generated by Django 5.0.14 on 2026-08-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=80, verbose_name="도시명")),
                (
                    "country_code",
                    models.CharField(max_length=2, verbose_name="국가 코드"),
                ),
                ("timezone", models.CharField(max_length=80, verbose_name="시간대")),
                ("active", models.BooleanField(default=True, verbose_name="사용 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "도시",
                "verbose_name_plural": "도시",
                "ordering": ["name_ko"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layover_count",
                    models.CharField(
                        choices=[
                            ("none", "없음"),
                            ("one", "1회"),
                            ("two_plus", "2회 이상"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="경유 횟수",
                    ),
                ),
                (
                    "total_flight_minutes",
                    models.PositiveIntegerField(verbose_name="총 비행시간"),
                ),
                (
                    "total_elapsed_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="총 경과시간"
                    ),
                ),
                (
                    "max_layover_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최장 대기시간"
                    ),
                ),
                (
                    "timezone_diff_minutes",
                    models.IntegerField(blank=True, null=True, verbose_name="시차"),
                ),
                (
                    "travel_direction",
                    models.CharField(
                        choices=[
                            ("east", "동행"),
                            ("west", "서행"),
                            ("none", "시차 없음"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="이동 방향",
                    ),
                ),
                (
                    "landing_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="착륙 시각"
                    ),
                ),
                (
                    "next_schedule_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 일정 시각"
                    ),
                ),
                (
                    "next_schedule_after_minutes",
                    models.PositiveIntegerField(verbose_name="다음 일정까지"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "등록됨"),
                            ("landed", "착륙함"),
                            ("recovering", "회복 중"),
                            ("done", "완료"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "expected_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="예상 점수"
                    ),
                ),
                (
                    "actual_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="실측 점수"
                    ),
                ),
                (
                    "current_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="현재 점수"
                    ),
                ),
                (
                    "target_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="목표 점수"
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="점수 근거"
                    ),
                ),
                (
                    "summary_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="요약 문구"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_trips",
                        to="trips.city",
                        verbose_name="도착지",
                    ),
                ),
                (
                    "origin_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_trips",
                        to="trips.city",
                        verbose_name="출발지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "여정",
                "verbose_name_plural": "여정",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["created", "landed", "recovering"])),
                fields=("user",),
                name="uniq_active_trip_per_user",
            ),
        ),
    ]
