# Generated by Django 5.0.14 on 2026-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='baseline_disruption_score',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='baseline_landing_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='baseline_recent_route',
        ),
        migrations.AddField(
            model_name='trip',
            name='has_recent_flight_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='장거리 비행 경험 여부'),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_flight_date',
            field=models.DateField(blank=True, null=True, verbose_name='마지막 비행 일자'),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_flight_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='마지막 비행 총 시간(분)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='typical_impact',
            field=models.CharField(blank=True, choices=[('none', '아무런 영향 없음'), ('quick', '도착 직후 회복됨'), ('slight', '살짝 피로함'), ('schedule', '일정에 영향 줌')], max_length=20, verbose_name='평소 컨디션 영향도'),
        ),
    ]
